### ISSUE TITLE
关于路径斜杠的问题

### ISSUE THREAD

**Issue by ZeronoFreya** [atticus-lv/super_io#15]
默认是`C:/Users/xxx/AppData/Roaming/../Local/Temp/ball.obj`
复制报错：系统找不到指定的文件
我用的三方软件TeraCopy，回馈官方根本不带理的
看日志发现这玩意只支持 `e:\Cache\立方体.obj`这样的路径，注意斜杠，个人一直分不清正反

请问这有好的解决办法吗？

**Comment by atticus-lv** [comment]
是导出时候的复制操作吗？能贴一下完整的报错信息吗？

**Comment by ZeronoFreya** [comment]
> 

报错信息就只有系统找不到指定的文件，没啥有用的。
我觉得插件本身没问题，纯粹是TeraCopy不识别“/”的问题。
我没读插件的代码，不知道把“/”换成“\\\”可不可以

**Comment by atticus-lv** [comment]
考虑到mac和大多数应用场景都是/，会添加一个输出路径的选项到偏好设置
