### ISSUE TITLE
导入导出时如果需要应用变换和坐标位置归0, 要怎么做设置?

### ISSUE THREAD

**Issue by SiulroKe** [atticus-lv/super_io#19]
我没有编程基础, 这里有两个问题想要问下, 
1. 我想导入模型FBX到unity, 在正常的导出流程中, 我需要勾选应用变换, 才能保证导出后模型的坐标轴朝向是正确的, 其次导出的时候我不想保留选中物体的坐标位置信息(x,y,z,都为0,0,0)那么我需要怎么设置?
导入模型的时候, 因为同事们使用的软件不同, 所以坐标系不同的缘故我需要对每个导入的模型进行一次应用变换, 又需要怎么去设置?

或许都是同一个问题吧, 但是我还是想一次性说清楚哈

**Comment by atticus-lv** [comment]
参考手册流程
![image](https://user-images.githubusercontent.com/64118610/157556756-f02744f7-f61b-4eb1-9d9c-f7daf8a4fa7e.png)
将导出fbx的命令复制到控制板，删掉括号后按tab得到参数（非必要）
打开偏好设置的python提示，开发者选项，将鼠标悬停在导出界面的参数ui上可以得到对应的参数名称，切换参数ui可以在下方信息面板得到具体数值
![image](https://user-images.githubusercontent.com/64118610/157557084-0f59287c-52b2-4740-af39-bdf43efbb234.png)
填入操作如下（记得保存或者导出设置）
![image](https://user-images.githubusercontent.com/64118610/157557604-3df27140-eebb-4a29-8532-6d0c811c8a2f.png)

**Comment by SiulroKe** [comment]
应用变换导出可以啦,那个导出时归零(位置信息为0,0,0)是不是做不了,  export_scene.fbx里面没有对应的命令来着
