### ISSUE TITLE
Can't support "sketchup_import" third-party addon

### ISSUE THREAD

**Issue by xz-blender** [atticus-lv/super_io#20]
Sketchup is the most used software in the architecture and landscape industry. 
The best and most convenient way to import SketchUp into Blender is to use the "Sketchup_Importer plugin".
The Addon link:
https://github.com/RedHaloStudio/Sketchup_Importer

**Comment by 18883234348** [comment]
Thank your contribution to blender!!😘

**Comment by atticus-lv** [comment]
Install that addon
Add a custom config like this
![image](https://user-images.githubusercontent.com/64118610/168020269-e70c0d33-3a87-42bd-8f04-02d7363fa130.png)
Now you can get it in the import menu
![image](https://user-images.githubusercontent.com/64118610/168020394-77e8c3f5-8c4a-492c-89d7-b259b5bfa719.png)

**Comment by xz-blender** [comment]
Thanks!!😘😘
