### ISSUE TITLE
在3.1.2上无法安装提示错误

### ISSUE THREAD

**Issue by SimonLuoshiping** [atticus-lv/super_io#22]
在blender 3.1.2上无法安装提示错误
![微信截图_20220523100225](https://user-images.githubusercontent.com/56295798/169729642-989283d8-1c2c-4e74-b6d2-3ce663a8f311.png)

**Comment by atticus-lv** [comment]
一般情况下建议用稳定版（release里面绿色的），这个错误是预览版1.4.5.1出现的，已经修复上传
