### ISSUE TITLE
世界资产预览渲染报错

### ISSUE THREAD

**Issue by shintsao** [atticus-lv/super_io#27]
blender版本3.0
报错信息如下
<img width="875" alt="屏幕快照 2022-06-11 下午6 22 28" src="https://user-images.githubusercontent.com/1567685/173184034-757851e7-9fb7-4dba-b9b5-8bd8c55fe517.png">

-----
后来在passport/blender asset 下自己新建文件夹asset_previews后不出现报错
但是此文件夹下也没有成功渲染缩略图

-----
blender升级到3.2版本后功能正常
（不过其他的复制黏贴功能都报错了T_T)
<img width="838" alt="屏幕快照 2022-06-11 下午6 42 06" src="https://user-images.githubusercontent.com/1567685/173184452-40978c27-83d9-405d-ba3a-d0f240acb3d8.png">

**Comment by atticus-lv** [comment]
由[6a75830](https://github.com/atticus-lv/super_io/pull/28/commits/6a75830b88cd0886793ca3bda3ae76fa381958a0)修复
