### ISSUE TITLE
Houdini Addon not showing

### ISSUE THREAD

**Issue by Kettenotter** [atticus-lv/super_io#30]
Actually Solved: moved SPIO.json to 
**C:\Users\Sebi\OneDrive\Documents\houdini19.0** 
from wrong path which Houdini doesn't detect
 **C:\Users\Sebi\Documents\houdini19.0** 
Its because in Windows 11 the Document folder is now under OneDrive which is annoying.

-
-
-
-
-
-

Solved: used the "Package Browser" window and there **>file>load package** and selected the SPIO.json. Now it shows up.
Perhaps add this to the Documentation. Can be hard to find for semi experienced users like myself.

![image](https://user-images.githubusercontent.com/32515271/175017532-b5fdcded-32b8-41d0-8c37-42dc1e2bbc36.png)

Houdini addon not showing up.
Installed the addon for Houdini 19 inside from Blender. I am using Houdini Inide 19.0.622.
Do I need to do something so that it finds the addon?
Because it's not showing up inside of the shelf tools. Attached some screenshots: 

![image](https://user-images.githubusercontent.com/32515271/175012897-e70d0968-180e-464f-8651-29b589698bda.png)
![image](https://user-images.githubusercontent.com/32515271/175012784-7c67ced3-6894-4d05-8adc-2a72f8afdd4c.png)

**Comment by atticus-lv** [comment]
oh, that is a question. I will check it( But my document is not in one drive)

**Comment by atticus-lv** [comment]
fix by ac44b8c34ee4760ddbb041e47faddb2c019f18cb
