### ISSUE TITLE
Not sure why it prevents B-renderon from working

### ISSUE THREAD

**Issue by xianqinlianqishi** [atticus-lv/super_io#32]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. Blender 3.1, spio 1.4.5.2]

**Additional context**

**Comment by atticus-lv** [comment]
can you give some screen shot for reporting this error?
And how your operate the b renderon?

**Comment by atticus-lv** [comment]
seem that you did not reply for a long time, I will close this issue. You can reopen it if you have any question
