### ISSUE TITLE
插件和Batch Render Creator这个批量渲染的软件有点冲突

### ISSUE THREAD

**Issue by chenpaner** [atticus-lv/super_io#33]
**和Batch Render Creator这个批量渲染的软件有点冲突**
你好，在启用这个插件后我用和Batch Render Creator这个批量渲染的软件加载项目时会卡死，我是用那个软件作者提示的方法一个个排除插件来找到这个插件冲突的，Batch Render 的介绍界面也说到有些插件会导致项目导入卡死，所以想问下能否帮忙结合那个软件看下是否有修复的可能！

Batch Render Creator软件的地址：https://blender-addons.gumroad.com/l/kAloE
我用的是blender3.2，superio1.4.6，Batch Render Creator2.0.2版本

**Comment by atticus-lv** [comment]
你说的加载时哪一个步骤，add project/add render我都可以正常使用，没法重现你的问题。
最好有录屏或者日志
PS：我的是付费版的2.1beta
![image](https://user-images.githubusercontent.com/64118610/191114249-d634a673-d39b-4527-9c1b-c994ab6f76fa.png)

**Comment by chenpaner** [comment]
添加blender文件后再点击+Add Render，就会不停的转圈，如果不勾选super_io插件再点击+Add Render就会正常进入

**Comment by atticus-lv** [comment]
用两个不同的版本测试了下，2.02的版本确实有这个问题，但2.1beta版本可以正常使用。
因为这个add render的步骤实际上是后台开了一个blender然后来读取文件，所以老版本应该是没有对插件的注册失败问题进行处理。
打不开有可能是为了兼容2.8而重复注册面板导致的错误（但实际打开blender并不影响），我会去调查下

**Comment by atticus-lv** [comment]
已修复 #45
