### ISSUE TITLE
目前已经有了开源直接拖放打开插件，希望此插件也可以集成直接拖入打开功能

### ISSUE THREAD

**Issue by waternight17** [atticus-lv/super_io#40]
刚刚发现了，可以直接拖放众多常用格式文件，直接在Blender中打开的插件。
分别是Blender Market的【Drag & Drop Import】，以及Github的【blender-drag-and-drop】，这种插件终于是出了😙。
不过【super_io】有着很多不可替代的功能，已经到了无法舍弃的地步，所以想知道【super_io】是否可以更近一步，也集成这个很有必要的功能呢！！
个人是非常希望加入这个功能的。

**Comment by atticus-lv** [comment]
这个拖拽面板是pyqt做的，实现的话不难，但可能会有冲突（接管其他窗口的拖拽行为，调整blender窗口尺寸时覆盖其他的应用等）
一开始是往拖拽那个方向做的，但是当时win11并不支持拖拽图标到应用文件，所以就没有实现。另外，这样制作的缺点是：
1.舍弃blender的特性（比如不同面板的行为等）
2.需要安装pyqt这个额外的库来实现简单的事件接收（大概300m）
当然也有更全面的拖拽解决方案，如资产管理软件connector就实现了不舍弃blender特性的拖拽（因为它做的是拖出自己的软件的行为，而不是拖入blender的行为，当然他们已经好久没更新了）

**Comment by atticus-lv** [comment]
第二个开源的还没看过，之后有空去研究下

**Comment by waternight17** [comment]
我本人并不会写代码，所以不太清楚你说的pyqt。
不过第二个开源插件总共就100多kb（不知道是不是和你使用了不同的构思或方法），在拖放导入很顺滑的情况下，还能够直接对导入格式做各种自定义行为，已经相当的方便了。
双方都是开源插件，但愿它有可以直接用来借鉴的地方，能把优秀的功能集中在一个插件中，那就太棒了。

**Comment by atticus-lv** [comment]
今天去看了第二个插件, 手撸汇编反向hook blender的函数...只能说牛逼，看不懂hhh。
文件小是因为把源码都编译了（就像blender 10g源码只有200m文件大小，而spio是纯脚本，不用编译），但是局限在blender的拖拽接受那，受限于拖拽单个文件...我再想想吧

**Comment by waternight17** [comment]
官方刚刚出了直接拖放导入obj文件的新分支：https://projects.blender.org/blender/blender/pulls/106871

**Comment by atticus-lv** [comment]
我会去看下，这段时间比较忙

**Comment by atticus-lv** [comment]
https://github.com/atticus-lv/CustomDragImport 新插件已集成
