### ISSUE TITLE
3.6 导入图片为平面报错

### ISSUE THREAD

**Issue by 1308511739** [atticus-lv/super_io#41]
Python: Traceback (most recent call last):
  File "D:\BLENDER\TOOL\addons\super_io\ops\op_image_io.py", line 65, in execute
    bpy.ops.import_image.to_plane(files=files, directory=dir, offset=True)
  File "D:\BLENDER\blender-3.6.0\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  IMPORT_IMAGE_OT_to_plane.files error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "type" missing

**Comment by atticus-lv** [comment]
开启默认的导入为平面的插件
