### ISSUE TITLE
3.5导出到C4D失效，但是C4D可以导出到blender C4D版本为2023.2

### ISSUE THREAD

**Issue by mimsober** [atticus-lv/super_io#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. Blender 3.1, spio 1.4.5.2]

**Additional context**

**Comment by atticus-lv** [comment]
是否有防火墙一类的软件拦截了blender

**Comment by atticus-lv** [comment]
太久没有回应，先关闭了。有需要可以打开
