### ISSUE TITLE
Blender won't exit when start from command line with SPIO enabled

### ISSUE THREAD

**Issue by HaiyiMei** [atticus-lv/super_io#44]
**Describe the bug**
When the SPIO addon is enabled, the blender won't quit when it is started from a command line like:
```bash
blender --background  --python-expr "print(1)"
```

------

**Screenshots**
![Snipaste_2023-09-16_22-29-26](https://github.com/atticus-lv/super_io/assets/35397764/7189df08-33c6-40af-80bc-81d0109ff080)

--------

![Snipaste_2023-09-16_22-28-37](https://github.com/atticus-lv/super_io/assets/35397764/da500d3e-dfb7-4961-9342-1aba299bcf47)

------

**Desktop:**
 - OS: Windows 10
 - Version: Blender 3.3, spio 1.4.7

**Comment by atticus-lv** [comment]
Try the latest version https://github.com/atticus-lv/super_io/releases/tag/v1.4.8

**Comment by HaiyiMei** [comment]
> Try the latest version [`v1.4.8` (release)](https://github.com/atticus-lv/super_io/releases/tag/v1.4.8)

Thanks for your quick reply. I upgraded to `v1.4.8`, but the same issue still remains.

![Snipaste_2023-09-17_12-16-34](https://github.com/atticus-lv/super_io/assets/35397764/5aac2d33-d518-4196-b30f-6182297b80e5)

**Comment by HaiyiMei** [comment]
I think I figured it out. Please see https://github.com/atticus-lv/super_io/pull/45

**Comment by atticus-lv** [comment]
Thanks! That helps a lot
