### ISSUE TITLE
 资产管理器 批量添加标签 作者等功能 失效 没反应版本3.6  

### ISSUE THREAD

**Issue by 879096600** [atticus-lv/super_io#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. Blender 3.1, spio 1.4.5.2]

**Additional context**

**Comment by atticus-lv** [comment]
我会去检查下，目前正在做4.0的适配

**Comment by atticus-lv** [comment]
fix4.0分支基本修复 https://github.com/atticus-lv/super_io/tree/fix-4.0
