### ISSUE TITLE
节点编辑器里右键上下文时会报错

### ISSUE THREAD

**Issue by chenpaner** [atticus-lv/super_io#48]
节点编辑器里右键上下文时会报错，好像这个操作是缺失的吧
C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Blender4addons\addons\super_io\ops\ops_super_import.py:268
rna_uiItemO: operator missing srna 'node.spio_import'

**Comment by atticus-lv** [comment]
新版本已修复
