### ISSUE TITLE
4.1版本很多功能不能正确使用，可以更新到支持4.X版本吗

### ISSUE THREAD

**Issue by TIRASING** [atticus-lv/super_io#49]
Python: Traceback (most recent call last):
  File "C:\Users\TR\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\super_io\addon\asset_helper\ops_set_preview.py", line 63, in execute
    current_library_name = context.area.spaces.active.params.asset_library_ref
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileAssetSelectParams' object has no attribute 'asset_library_ref'. Did you mean: 'asset_library_reference'?

**Comment by LiJT** [comment]
这个插件仿佛已经被荒废了

**Comment by atticus-lv** [comment]
抱歉，修复的版本一直放在了fix-4.0的分支。那个可以正常使用。现在已经合并了 @LiJT @TIRASING
