### ISSUE TITLE
3.0 正式版无法启用插件

### ISSUE THREAD

**Issue by rogerism** [atticus-lv/super_io#9]
你好，我使用Blender 3.0正式版（Steam版及官方压缩包），均无法启用插件。
提示：ModuleNotFoundError: No module named 'RenderNode-1'

抱歉由于开了多个页面，我发错项目了。

**Comment by atticus-lv** [comment]
这应该是插件文件夹命名所导致的问题
将其重命名为`RenderNode`即可
